### ISSUE TITLE
Max Payne 2 incompatibility

### ISSUE THREAD

**Issue by deton24** [VolsandJezuz/Rinput-Library#3]
I used this one:
https://fearless-assassins.com/files/file/1656-rinput/
And it prevents cursor from moving properly in the game. It is just pointed to the ground.
Probably in MP1 will be the same.

Maybe it's because the game uses dinput.dll instead of dinput8.dll, and it has something to do with injector's structure. I'm not sure.

**Comment by VolsandJezuz** [comment]
See response on MP3 incompatibility issue. Thanks
